[project]
name = "idacg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rio", email = "rio@kato.com" }
]
requires-python = ">=3.14"
dependencies = [
    "idapro>=0.0.10",
    "tree-sitter>=0.26.0",
    "tree-sitter-c>=0.24.2",
]

[project.scripts]
idacg = "idacg:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
build = ["lark"]
