set shell := ["bash", "-cu"]
set working-directory := justfile_directory()

rootfs := "rootfs"
dumps := "dumps"
targets := "targets.txt"
types := "types.h"
til := "types.til"

dump:
    grep -vE '^[[:space:]]*(#|$)' "{{targets}}" | \
    while IFS= read -r target; do \
        out="{{dumps}}/$$target"; \
        mkdir -p "$$(dirname "$$out")"; \
        idacg dump "{{rootfs}}/$$target" "$$out"; \
    done

import:
    idacg render import \
        functions='@{{dumps}}/**/*.func.jsonl' \
        calls='@{{dumps}}/**/*.call.jsonl' \
    | cypher-shell

search query:
    idacg search '{{dumps}}/**/*.func.jsonl' {{quote(query)}}

type:
    tilib -c -h"{{types}}" "{{til}}"
    grep -vE '^[[:space:]]*(#|$)' "{{targets}}" | \
    while IFS= read -r target; do \
        idacg type "{{rootfs}}/$$target" "{{til}}"; \
    done
